"""
train.py
========
Trains all four neural integrator models (PINN-symplectic, HNN, SympNet,
Boris+Corrector) on the reference Boris trajectory datasets generated by
dataset_generation.py, and saves weights to /checkpoints.

This is a demonstration-grade but real training run: modest epoch counts
(a few hundred) and dataset sizes (tens of thousands of samples) so the
whole pipeline runs to completion on CPU in a few minutes, while remaining
a genuine gradient-descent optimization exhibiting real loss decay.

Usage:
    python training/train.py
"""

import os
import sys
import time
import json

import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from common import set_global_seed, SEED, CHECKPOINT_DIR, get_logger, log_run_params
from training.dataset_generation import (build_and_save_all, load_combined_dataset,
                                          build_and_save_corrector_dataset, load_corrector_dataset)
from models.pinn_symplectic import build_model as build_pinn, LR as LR_PINN
from models.hnn import build_model as build_hnn, LR as LR_HNN
from models.sympnet import build_model as build_symp, LR as LR_SYMP
from models.boris_corrector import build_model as build_bc, LR as LR_BC
from models.boris import boris_step
from fields import UniformField, DipoleField, StochasticField

logger = get_logger("train")

EPOCHS = 200
BATCH_SIZE = 1024
DEVICE = "cpu"

TRAIN_FIELDS = {
    "uniform": UniformField(B0=1.0),
    "dipole": DipoleField(B0=1.0, r0=5.0),
    "stochastic": StochasticField(B0=1.0, eps=0.15, omega=0.5, seed=SEED),
}


def to_tensor(x):
    return torch.tensor(x, dtype=torch.float32, device=DEVICE)


def vectorized_boris_step(r, v, B, dt, q=-1.0, m=1.0):
    """Fully vectorized Boris step for arrays of shape (N,3) / (N,) dt,
    with E=0 (fields already sampled into B). Used to precompute the Boris
    baseline for the whole Boris+Corrector training set efficiently."""
    dt = dt[:, None]
    qmdt2 = 0.5 * q * dt / m
    v_minus = v  # E=0
    t_vec = qmdt2 * B
    t_mag2 = np.sum(t_vec * t_vec, axis=-1, keepdims=True)
    s_vec = 2.0 * t_vec / (1.0 + t_mag2)
    v_prime = v_minus + np.cross(v_minus, t_vec)
    v_plus = v_minus + np.cross(v_prime, s_vec)
    v_new = v_plus  # E=0
    r_new = r + v_new * dt
    return r_new, v_new


def make_loader(data, batch_size=BATCH_SIZE, shuffle=True):
    ds = TensorDataset(
        to_tensor(data["r"]), to_tensor(data["v"]), to_tensor(data["B"]),
        to_tensor(data["dt"]), to_tensor(data["r_next"]), to_tensor(data["v_next"]),
        to_tensor(data["drdt"]), to_tensor(data["dvdt"]),
    )
    return DataLoader(ds, batch_size=batch_size, shuffle=shuffle)


def train_pinn(train_data, val_data, epochs=EPOCHS):
    logger.info("=== Training PINN-symplectic ===")
    set_global_seed(SEED)
    model = build_pinn().to(DEVICE)
    opt = torch.optim.Adam(model.parameters(), lr=LR_PINN)
    loader = make_loader(train_data)
    history = []
    for epoch in range(epochs):
        model.train()
        epoch_loss = 0.0
        n_batches = 0
        for r, v, B, dt, r_next, v_next, drdt, dvdt in loader:
            opt.zero_grad()
            r_pred, v_pred = model(r, v, B, dt)
            loss, parts = model.physics_loss(r, v, r_pred, v_pred, r_next, v_next)
            loss.backward()
            opt.step()
            epoch_loss += loss.item()
            n_batches += 1
        avg_loss = epoch_loss / n_batches
        history.append(avg_loss)
        if epoch % 50 == 0 or epoch == epochs - 1:
            logger.info(f"[PINN-symplectic] epoch {epoch:4d}/{epochs}  loss={avg_loss:.6e}")
    return model, history


def train_hnn(train_data, val_data, epochs=EPOCHS):
    logger.info("=== Training HNN ===")
    set_global_seed(SEED)
    model = build_hnn().to(DEVICE)
    opt = torch.optim.Adam(model.parameters(), lr=LR_HNN)
    loader = make_loader(train_data)
    history = []
    model.train()
    for epoch in range(epochs):
        epoch_loss = 0.0
        n_batches = 0
        for r, v, B, dt, r_next, v_next, drdt, dvdt in loader:
            opt.zero_grad()
            drdt_pred, dvdt_pred = model(r, v, B)
            loss, parts = model.physics_loss(drdt_pred, dvdt_pred, drdt, dvdt)
            loss.backward()
            opt.step()
            epoch_loss += loss.item()
            n_batches += 1
        avg_loss = epoch_loss / n_batches
        history.append(avg_loss)
        if epoch % 50 == 0 or epoch == epochs - 1:
            logger.info(f"[HNN] epoch {epoch:4d}/{epochs}  loss={avg_loss:.6e}")
    return model, history


def train_sympnet(train_data, val_data, epochs=EPOCHS):
    logger.info("=== Training SympNet ===")
    set_global_seed(SEED)
    model = build_symp().to(DEVICE)
    opt = torch.optim.Adam(model.parameters(), lr=LR_SYMP)
    loader = make_loader(train_data)
    history = []
    for epoch in range(epochs):
        model.train()
        epoch_loss = 0.0
        n_batches = 0
        for r, v, B, dt, r_next, v_next, drdt, dvdt in loader:
            opt.zero_grad()
            dt_scalar = dt.mean()
            r_pred, v_pred = model(r, v, dt_scalar)
            loss, parts = model.physics_loss(r_pred, v_pred, r_next, v_next)
            loss.backward()
            opt.step()
            epoch_loss += loss.item()
            n_batches += 1
        avg_loss = epoch_loss / n_batches
        history.append(avg_loss)
        if epoch % 50 == 0 or epoch == epochs - 1:
            logger.info(f"[SympNet] epoch {epoch:4d}/{epochs}  loss={avg_loss:.6e}")
    return model, history


def train_boris_corrector(train_data, val_data, epochs=EPOCHS):
    logger.info("=== Training Boris + Corrector ===")
    set_global_seed(SEED)
    model = build_bc().to(DEVICE)
    opt = torch.optim.Adam(model.parameters(), lr=LR_BC)

    # Precompute Boris predictions (numpy, fully vectorized) for the whole
    # training set -- the Boris step itself is not learned/differentiated.
    # NOTE: train_data here is the MULTI-SCALE dataset (dt in [0.02, 0.16])
    # so the corrector learns how the required correction scales with dt,
    # which is essential for it to generalize to the larger steps used in
    # the B4 decaying-field stress test (Figure 4).
    r_np, v_np, B_np, dt_np = train_data["r"], train_data["v"], train_data["B"], train_data["dt"]
    r_boris, v_boris = vectorized_boris_step(r_np, v_np, B_np, dt_np[:, 0])

    ds = TensorDataset(
        to_tensor(r_np), to_tensor(v_np), to_tensor(B_np), to_tensor(dt_np),
        to_tensor(r_boris), to_tensor(v_boris),
        to_tensor(train_data["r_next"]), to_tensor(train_data["v_next"]),
    )
    loader = DataLoader(ds, batch_size=BATCH_SIZE, shuffle=True)

    history = []
    for epoch in range(epochs):
        model.train()
        epoch_loss = 0.0
        n_batches = 0
        for r, v, B, dt, r_b, v_b, r_next, v_next in loader:
            opt.zero_grad()
            delta_r, delta_v = model(r, v, B, dt)
            loss, parts = model.physics_loss(r_b, v_b, delta_r, delta_v, r_next, v_next)
            loss.backward()
            opt.step()
            epoch_loss += loss.item()
            n_batches += 1
        avg_loss = epoch_loss / n_batches
        history.append(avg_loss)
        if epoch % 50 == 0 or epoch == epochs - 1:
            logger.info(f"[Boris+Corrector] epoch {epoch:4d}/{epochs}  loss={avg_loss:.6e}")
    return model, history


def main():
    set_global_seed(SEED)
    t0 = time.time()

    run_params = {
        "seed": SEED,
        "epochs": EPOCHS,
        "batch_size": BATCH_SIZE,
        "device": DEVICE,
        "train_fields": list(TRAIN_FIELDS.keys()),
        "lr_pinn": LR_PINN, "lr_hnn": LR_HNN, "lr_sympnet": LR_SYMP, "lr_boris_corrector": LR_BC,
    }
    log_run_params(logger, run_params)

    logger.info("Ensuring reference datasets exist ...")
    build_and_save_all(force=False)
    build_and_save_corrector_dataset(force=False)

    logger.info("Loading combined training/validation data ...")
    train_data = load_combined_dataset("train")
    val_data = load_combined_dataset("val")
    logger.info(f"Train samples: {train_data['r'].shape[0]}, Val samples: {val_data['r'].shape[0]}")

    corrector_train_data = load_corrector_dataset("train")
    logger.info(f"Boris+Corrector multi-scale train samples: {corrector_train_data['r'].shape[0]}")

    histories = {}

    model_pinn, hist_pinn = train_pinn(train_data, val_data)
    torch.save(model_pinn.state_dict(), os.path.join(CHECKPOINT_DIR, "pinn_symplectic.pt"))
    histories["pinn_symplectic"] = hist_pinn

    model_hnn, hist_hnn = train_hnn(train_data, val_data)
    torch.save(model_hnn.state_dict(), os.path.join(CHECKPOINT_DIR, "hnn.pt"))
    histories["hnn"] = hist_hnn

    model_symp, hist_symp = train_sympnet(train_data, val_data)
    torch.save(model_symp.state_dict(), os.path.join(CHECKPOINT_DIR, "sympnet.pt"))
    histories["sympnet"] = hist_symp

    model_bc, hist_bc = train_boris_corrector(corrector_train_data, val_data)
    torch.save(model_bc.state_dict(), os.path.join(CHECKPOINT_DIR, "boris_corrector.pt"))
    histories["boris_corrector"] = hist_bc

    with open(os.path.join(CHECKPOINT_DIR, "training_history.json"), "w") as f:
        json.dump(histories, f, indent=2)

    with open(os.path.join(CHECKPOINT_DIR, "run_params.json"), "w") as f:
        json.dump(run_params, f, indent=2)

    dt_elapsed = time.time() - t0
    logger.info(f"All models trained and saved to {CHECKPOINT_DIR}. "
                f"Total training time: {dt_elapsed:.1f} s")


if __name__ == "__main__":
    main()
